### ISSUE TITLE
API error when trying to auth. 

### ISSUE THREAD

**Issue by Wisperer** [athrowaway2021/comix#23]
```Getting auth token . . .
{"response": {"challenge": {"challenge_reason": "AuthenticationFailed", "uri": "https://www.amazon.com/ap/challenge?arb=14c7afd4-2ad6-4249-8564-cb60fb081415", "required_authentication_method": "GenericClaimPassword"}}, "request_id": "0825dd8f55734e85b7f3a0d7af1a62c2"}
Traceback (most recent call last):
  File "/home/fletcher/comix/comix.py", line 142, in <module>
    cmx = Cmx(None)
  File "/home/fletcher/comix/comix.py", line 23, in __init__
    self.auth_token = amazon_api.login(config.EMAIL, config.PASSWORD)["access_token"]
TypeError: 'NoneType' object is not subscriptable
```

Known good password and email. Works fine with an older version of the script. 

Ran with `python comix.py list' after adding account info to config.py

**Comment by workingjb** [comment]
I suspect this is due to the site shifting from comixology to read.kindle.com, and the headers still referencing comixology.comics.

**Comment by KaHooli** [comment]
I'm getting the same issue...
```bash
Getting auth token . . .
{"response": {"challenge": {"challenge_reason": "HandleOnWebView", "uri": "https://www.amazon.com/ap/challenge?arb=<removed>"}}, "request_id": "<removed>"}
Traceback (most recent call last):
  File "/home/james/comix/comix.py", line 142, in <module>
    cmx = Cmx(None)
  File "/home/james/comix/comix.py", line 23, in __init__
    self.auth_token = amazon_api.login(config.EMAIL, config.PASSWORD)["access_token"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by comment-account** [comment]
Try going to Amazon.com in your web browser, logging out of your account, and then logging back on again.  I think this following line is the clue:

{"response": {"challenge": {"challenge_reason": "HandleOnWebView", "uri": "https://www.amazon.com/ap/challenge?arb=<removed>"}}, "request_id": "<removed>"}

What happened for me is that I needed to respond to a prompt that it is actually me trying to login.  You can't get at that prompt using the script, but it appears reconfirming in the web browser that you are you is enough so that it stops happening in the script.  I generally use Linux but loaded the script in Windows and I ran into this exact situation.  Once I confirmed things in the browser, the script worked fine.

**Comment by athrowaway2021** [comment]
The above reply is correct, 3309195bd433f911dd2b10b76120875a966a3eb1 adds a message that tells users with 2FA to relogin in browser if this issue occurs.
