### ISSUE TITLE
Could not find any book associated with this account

### ISSUE THREAD

**Issue by notklm92** [athrowaway2021/comix#49]
I've been able to use this before with no issues but now I'm receiving 
> Could not find any book associated with this account . . . 

What should I do.

**Comment by rando2345** [comment]
The old cmx api is dead atm. No idea what's going to happen next.

**Comment by Pocokk** [comment]
Is this still broken?

**Comment by noaione** [comment]
> While I'm not sure which specific Kindle platforms are eligible for downloading HD content, it seems a recent version of Android and a high DPI device is enough.

I did test using Android 11 3840x2160 320dpi on Bluestacks, it works fine.
Be careful to not export it immediately since they actually have two-step download process for HD content.

> likely not offered in the same quality as older ComiXology releases.

I can see a more obvious JPEG artifact on the image (reprocessed JPEG...?) but the "quality" param used if `imagemagick` can be believed seems to be higher.

- `danke-Empire` rip: x3713 q92
    - Optimized: ~376mb
- Post-app merge (or whatever you want to call it): x3713 q96
    - Still in KFX format (DeDRM'd): ~628mb (Oh hey! It's close to the number listed in Amazon)
    - Run through KFX Input to CBZ/ZIP conversion: ~527mb (non-optimized), ~494mb (optimized)
    
Might edit this comment to show some actual diff.

**Comment by noaione** [comment]
> While I'm not sure which specific Kindle platforms are eligible for downloading HD content, it seems a recent version of Android and a high DPI device is enough.

Anything around 2K screen with 320+ DPI I think should be enough I think, you can always check if you get double download notification for your older stuff (and an obvious KFX file format)

> likely not offered in the same quality as older ComiXology releases.

I can see a more obvious JPEG artifact on the image (reprocessed JPEG...?) but the "quality" param used if `imagemagick` can be believed seems to be higher.

- `danke-Empire` rip: x3713 q92
    - Optimized: ~376mb
- Post-app merge (or whatever you want to call it): x3713 q96
    - Still in KFX format (DeDRM'd): ~628mb (Oh hey! It's close to the number listed in Amazon)
    - Run through KFX Input to CBZ/ZIP conversion: ~527mb (non-optimized), ~494mb (optimized)
    
Might edit this comment to show some actual diff.

*Reposted because reason*

**Comment by noaione** [comment]
I think changing some line to force saving as PNG would work to at least not get a recompressed JPEG. I look at the code and most of the resaving occurs in `kfxlib/resources.py`

**Comment by noaione** [comment]
[KFX Input Mod.zip](https://github.com/athrowaway2021/comix/files/13684541/KFX.Input.Mod.zip)

Quick modification based on v2.6.0, use the calibre-debug CLI:
`calibre-debug -r "KFX Input" -- -z -l Book.kfx` (either use `--lossless` or `-l`, only support CBZ/PDF)

As a side note, this would make the output bigger and slower to process (PNG takes longer to save)

The new Kindle HD didn't looks that much worse with pretty similar JPEG artifacts to CMX HD as far as I can see. Although, if you're a purist, this is 100% not the same quality as original CMX HD.

**Comment by noaione** [comment]
Alright, after more testing this should fix some problems that I ran into:

[KFX Input Mod.zip](https://github.com/athrowaway2021/comix/files/13684845/KFX.Input.Mod.zip)

The only problem is that PNG is saved with JPEG extension but I'm too lazy to fix it

**Comment by salami-ch** [comment]
Very interesting! I tried to follow the linked guides, unfortunately I'm still getting the following error:
`calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container xxx.kfx has DRM and cannot be converted`

I have successfully extracted, converted and imported my keyfile and the book shows up in the Calibre library correctly. Does anyone have a clue what I might be missing? Thanks!

**Comment by noaione** [comment]
@salami-ch 

You would also need to replace one line of code in DeDRM plugin, the author in [discussion thread](https://github.com/noDRM/DeDRM_tools/discussions/440#discussioncomment-7871341) recently provide an edited version if you haven't replaced your version yet.

If you properly setup everything, this is how the imported KFX books looks like:

![image](https://github.com/athrowaway2021/comix/assets/34302902/fdb371ad-9946-44af-acf6-2475ed2cd3d4)

Note: That it said `Formats: KFX` and not `Formats: KFX-ZIP` (KFX-ZIP -> Fails to DeDRM)

If you're backing up something that you know is a HD comics (above x2600 resolutions), make sure that the size of the folder is similar to what Amazon advertises in their website (or check if the folder in `Android/data/com.amazon.kindle/files/ASIN` if the folder size keep growing after you got a finished download notification)

![image](https://github.com/athrowaway2021/comix/assets/34302902/80e9460b-cd00-4911-84b5-aff6d896cc7c)

To make it easier, you can just ZIP all the files of the KFX(s) folder, name it to `BOOK_ASIN.kfx-zip` and import it to Calibre to make it more consistent.

![image](https://github.com/athrowaway2021/comix/assets/34302902/66a6ea8b-3e2c-49ca-9515-9d2eedb29d95)

**Comment by salami-ch** [comment]
Thanks for the detailed hints @noaione

Looks like I have already correctly performed these steps. My mistake was to specify the source files rather than the resulting kfx in the Calibre library after import. I was assuming that the calibre CLI would imvoke DeDRM on the fly, but apparently this process is only performed during the library import.

I can now successfully convert a recently published comic in its full x3056 resolution. You guys are awsome, thanks a lot!

**Comment by 2023comicjtr** [comment]
It is fantastic to have this back, but does anyone know of any way to get the cover in full 1988x3056 resolution?  So far I'm only getting the old Kindle cover of 1249x1920.  Even if you unpack the KFX file instead of converting to CBZ, the cover is still the lower resolution version.  Apparently the scene groups have figured it out (help?), but they would have no reason to talk to me, so I figured I'd ask here.  Thanks!

**Comment by noaione** [comment]
I don't think so, the easiest way is to just get the cover from Amazon website and denoise it. The cover is usually around x2560 so it's good enough for most people.

You can use this bookmarklet to easily get the "high quality" cover: https://github.com/rRoler/bookmarklets#amazon
1. Click Bookmarklet code
2. Click `Raw`
3. Copy the `javascript:xxxxxxxxxxxxxxxxxxx` line
4. Create new browser bookmark and paste it to the URL box

You can just then go to the book page in Amazon and click the bookmark

**Comment by 2023comicjtr** [comment]
Thanks!  That's super helpful.  I do generally grab those covers, but had been going to this site to get them: https://www.ereader-palace.com/get-high-resolution-cover-image-amazon-kindle-ebooks/

The bookmarklet is much more convenient. :-)

**Comment by 2023comicjtr** [comment]
> If you have a method of finding the "ComiXology ID" of a book...

Sadly, I'm not well-versed enough in Python to come up with a script, and even though brute-forcing a range of values isn't totally off-putting, I don't understand wget/curl enough to come up with a command that allows for both the folder name and the file name increasing incrementally.  Thanks for doing so much checking though; much appreciated!

**Comment by 2023comicjtr** [comment]
I had that happen a couple of times.  Once I just dumped everything from the update folder into the main one (replacing everything in the main folder with the files from the update folder if they had the same name), and I could then process the main folder.  The other time I could just process the update folder on its own (since it had the metadata file and drm-voucher).  I think one time nothing worked and I had to redownload.

**Comment by athrowaway2021** [comment]
@neckothy @mslmn @2023comicjtr @noaione 

The new unkindle tool should now work to get highest possible quality for both old ComiXology titles and post-merge titles. I've tested it with a few and I'm getting x3056 outputs for Ultimate Spider-Man (2024) for example.

The only major issue now is that the covers are all still x1920 and I haven't seen any way to reliably get ComiXology IDs for books to get the HD covers like mentioned here previously.
